app/Http/routes.php
<?php

Route::get('/', ['as' => 'home', 'uses' => 'Frontend\PostController@index']);
Route::get('/post/{alias}', ['as' => 'show-post', 'uses' => 'Frontend\PostController@show']);

//Route::post('/post','UploadController@store');

Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/home', 'HomeController@index');
    Route::get('pload','UploadController@getForm');
   //Route::post('Upload','UploadController@store');
    Route::post('/pload', ['as' => 'upload-image', 'uses' => 'UploadController@store']);
    Route::resource('blog', 'Backend\BlogController');
    Route::controller('filemanager', 'FilemanagerLaravelController');
});

app/Blog.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model {

    protected $table    = 'blog';
    protected $fillable = ['user_id', 'alias', 'title', 'body', 'timestamp', 'status'];
    public $rules       = [
        'title' => 'required',
        'body'  => 'required',
    ];

}

app/Http/Controllers/Backend/BlogController.php
<?php namespace App\Http\Controllers\Backend;

use App\Blog;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\User;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;

class BlogController extends Controller {

    protected $user;
    protected $blog;

    public function __construct(Blog $blog, User $user){
        $this->middleware('auth');
        $this->user = $user;
        $this->blog = $blog;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Resource
     */
    public function index(){
        $user_id = auth()->user()->id;
        $posts = $this->blog->where('user_id', $user_id)->orderBy('id', 'DESC')->paginate(5);

        foreach($posts as $post){

            $post->date_time = date('Y-m-d H:i:s', $post->timestamp);
        }


        return view('Backend.blog.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Resource
     */
    public function create(){
        return view('Backend.blog.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Resource
     */
    public function store(){
        $input               = Input::all();
        $valid               = Validator::make($input, $this->blog->rules);

        if($valid->fails()){
            return redirect('blog/create')
                ->withErrors($valid)
                ->withInput()
                ->with('message', 'There were validation errors!');
        }

        $input['user_id']    = auth()->user()->id;
        $input['timestamp']  = strtotime(date('Y-m-d H:i:s'));
        $input['status']     = 1;
        $blog                = $this->blog->fill($input);

        if($blog->save()){

            $input['alias']  = $this->createAlias($blog->id, $input['title']);
            $blog          = $this->blog->fill($input);
            $blog->save();

            return redirect()->route('blog.index')->with('message', 'Create Post Successfully.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Resource
     */
    public function show($id){
        $show_post = $this->blog->find($id);
        $show_post->user_name = $this->user->find($show_post->user_id)->name;

        return view('Backend.blog.index', compact('show_post'));
    }

    /**
     * Update the specified resource.
     *
     * @param int $id
     * @return Resource
     */
    public function edit($id){
        $post = $this->blog->find($id);

        return view('Backend.blog.form', compact('post'));
    }

    /**
     * Display the specified resource in storage.
     *
     * @param int $id
     * @return Resource
     */
    public function update($id){
        $input = Input::all();
        $valid = Validator::make($input, $this->blog->rules);

        if($valid->fails()){
            return redirect('blog/edit')
                ->withErrors($valid)
                ->withInput()
                ->with('message', 'There were validation errors!');
        }

        $input['alias'] = self::createAlias($input['title'], $id);

        $this->blog     = $this->blog->find($id);
        $post           = $this->blog->fill($input);

        if($post->save()){
            return redirect()->route('blog.index')->with('message', 'update successfully.');
        }
		
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Resource
     */
    public function destroy($id){
        $this->blog->find($id)->delete();

        return redirect()->route('blog.index');
    }

    /**
     * Create alias for post
     *
     * @param int $id, $title
     * @return Resource
     */
    private function createAlias($id, $title){
        $strtolower_title = strtolower($title);
        $alias            = str_replace('–', ' ', $strtolower_title);
        $alias            = str_replace(' ', '-', $alias);
        $alias            = str_replace('--', '-', $alias);
        $alias            = str_replace('--', '-', $alias);
        $alias            = $id.'-'.$alias;

        return $alias;
    }

}

resources/views/backend/blog/form.blade.php
@extends('layouts.app')

@section('content')
    <div class="container spark-screen">
        <div class="row" style="margin-bottom: 100px;">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">@if(isset($post)) Edit post @else Create new post @endif</div>

                    @if(Session::has('message'))
                        <div class="panel-body">
                            <div id="message" class="input-group">
                                <div class="btn-group" aria-describedby="basic-addon1">{!! Session::get('message') !!}</div>
                                {{--<span class="btn-group fa fa-times close input-group-addon" id="basic-addon1"></span>--}}
                            </div>
                        </div>
                    @endif

                    <div class="panel-body">
                        @if(isset($post))
                            {!! Form::model($post, ['method' => 'PUT', 'route' => ['blog.update', $post->id], 'files' => true]) !!}
                        @else
                            {!! Form::open(['method' => 'POST', 'route' => 'blog.store', 'files' => true]) !!}
                        @endif
                                <div class="input-group">
                                    <span class="input-group-addon" id="basic-addon1">Title :</span>
                                    {!! Form::text('title', null, ['class'=>'form-control title', 'aria-describedby'=>'basic-addon1']) !!}
                                </div>
                                <br><br>
                                <div class="input-group">
                                    <span class="input-group-addon" id="basic-addon2">Body :</span>
                                    {!! Form::textarea('body', null, ['class'=>'form-control', 'aria-describedby'=>'basic-addon2']) !!}
                                </div>
                                <br><br>

                                <div class="input-group">
                                    <div class="btn-group group-post-btn">
                                        @if(isset($post))
                                            {!! Form::submit('Update Post', ['class' => 'btn btn-info submit-send-post']) !!}
                                        @else
                                            {!! Form::submit('Save Post', ['class' => 'btn btn-info submit-send-post']) !!}
                                        @endif
                                    </div>
                                    <div class="btn-group group-post-btn"><a href="{{ URL::route('blog.index') }}" class="btn btn-danger callback-post">Cancel</a></div>
                                </div>

                            {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script type="text/javascript" src="{{ url('') }}/tinymce/tinymce.min.js"></script>
    <script type="text/javascript" src="{{ url('') }}/tinymce/tinymce_editor.js"></script>
    <script type="text/javascript">
        editor_config.selector      = "textarea";
        editor_config.path_absolute = "http://localhost:8000/";
        tinymce.init(editor_config);
    </script>
@endsection

resources/views/backend/blog/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container spark-screen">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                @if(!isset($show_post))
                    <div class="create-post"><a href="{{ URL::route('blog.create') }}" class="btn btn-success"><i class="fa fa-plus-square"></i> Add Post</a></div>
                    <br>
                @endif

                <div class="panel panel-default">
                    <div class="panel-heading">@if(isset($show_post)) {!! $show_post->title !!} @else List Of Posts @endif</div>

                    @if(isset($show_post))
                        <div class="panel-body">
                            {!! $show_post->body !!}
                        </div>
                        <hr>
                        <p style="text-align: center;">Author : {!! $show_post->user_name !!} | <a href="{{ URL::route('blog.index') }}">Back</a></p>
                    @else
                        @if(Session::has('message'))
                            <div class="panel-body">
                                <div id="message" class="input-group">
                                    <div class="btn-group" aria-describedby="basic-addon1">{!! Session::get('message') !!}</div>
                                    {{--<span class="btn-group fa fa-times close input-group-addon" id="basic-addon1"></span>--}}
                                </div>
                            </div>
                        @endif

                        <div class="panel-body">
                            @if($posts->count())
                                <table class="table table-striped table-bordered table-hover publish">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Date & Time</th>
                                        <th>Title</th>
                                        <th>Show Post</th>
                                        <th>Edit Post</th>
                                        <th>Delete Post</th>
                                        <th>Publish</th>
                                    </tr>
                                    </thead>

                                    <tbody>
                                    <?php $i=1; ?>
                                    @foreach($posts as $post)
                                        <tr>
                                            <td>{{ $i++ }}</td>
                                            <td>{{ $post->date_time }}</td>
                                            <td>{{ substr($post->title, 0, 80) }}</td>
                                            <td>
                                                <center>
                                                    <a href="{{ URL::route('blog.show', $post->id) }}" class="btn btn-primary"><i class="fa fa-eye"></i> Show</a>
                                                </center>
                                            </td>
                                            <td>
                                                <center>
                                                    <a href="{{ URL::route('blog.edit', $post->id) }}" class="btn btn-info"><i class="fa fa-edit"></i> Edit</a>
                                                </center>
                                            </td>
                                            <td class="del">
                                                <center>
                                                    {!! Form::open(['method' => 'DELETE', 'route' => ['blog.destroy', $post->id]]) !!}
                                                    <button class='btn btn-danger' type="submit" value="delete"><span class="fa fa-trash-o"></span> Delete</button>
                                                    {!! Form::close() !!}
                                                </center>
                                            </td>
                                            <td>
                                                <a class="status btn {!! (isset($post->status) && $post->status) ? 'btn-success' : 'btn-warning' !!}" data-token="{!! csrf_token() !!}" data-value="{!! $post->status !!}" data-url="#"><i class="fa {!! (isset($post->status) && $post->status) ? 'fa-eye' : 'fa-eye-slash' !!}"></i> {!! (isset($post->status) && $post->status) ? 'Published' : 'Unpublish' !!} </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>

                                <div class="paging">
                                    <center>
                                        {!! $posts->render() !!}
                                    </center>
                                </div>
                            @else
                                Nothing found!
                            @endif
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection